name: enfluwence
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.3.7
  get: ^4.6.6
  go_router: ^13.2.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logos/
    - assets/images/
    - assets/data/
    
  uses-material-design: true
